[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_launchpad = "CbhxF7aBq9iPP463ALGPnDZtZgs5cHQjkGgM3kEtiUZi"

[programs.devnet]
solana_launchpad = "CbhxF7aBq9iPP463ALGPnDZtZgs5cHQjkGgM3kEtiUZi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=e26bf879-6bb4-49c0-aafa-8e4d86687455"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
